###
POST http://localhost:3000/api/users HTTP/1.1
Content-Type: application/json

{
    "name":"Jose chungus",
    "email":"MetaJose@gmail.com",
    "password":"Reparto123",
    "preference": ["Peruana", "Brazilena"],
    "active":true

}

###
GET http://localhost:3000/api/users HTTP/1.1


###
GET http://localhost:3000/api/users/66c7daf88332a9a05ee5f802 HTTP/1.1


###
PUT http://localhost:3000/api/users/66c97760d4ed89a2eb44819b HTTP/1.1
Content-Type: application/json

{
    "name":"Pedro Mendez",
    "email":"Lopster@gmail.com",
    "preference": ["Arabe", "Italiana"],
    "active":true
}

###
DELETE http://localhost:3000/api/users/66c7daf88332a9a05ee5f802 HTTP/1.1
